#![allow(non_snake_case)]


extern crate cpp_build;
extern crate cc;


use ::cc::Build;
use ::cpp_build::Config;


fn main()
{
	compileCPlusPlusGlueCode();
	compileDCMTKLibrary();
}

fn compileCPlusPlusGlueCode()
{
	Config::new()
        .include("lib/dcmtk/dcmdata/libsrc")
        .include("lib/dcmtk/ofstd/libsrc")
        .include("lib/dcmtk/oflog/libsrc")
        .flag("-w")
        .build("src/main.rs");
}

fn compileDCMTKLibrary()
{
	Build::new()
	.cpp(true)
	.shared_flag(false)
	.static_flag(true)
	.warnings(false)
	.opt_level(0)
	.debug(false)
	.flag("-std=c++11")
    .flag("-lz")
	.include("lib/dcmtk_include")
    .file("lib/dcmtk/dcmdata/libsrc/vrscanl.c")
    .file("lib/dcmtk/dcmdata/libsrc/cmdlnarg.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdicent.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcfilter.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dclist.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcpath.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcrledrg.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dctagkey.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrda.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrobow.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrsl.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrulup.cc")
    .file("lib/dcmtk/dcmdata/libsrc/mkdictbi.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcbytstr.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdictbi.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dchashdi.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcmatch.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcpcache.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcrleerg.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dctypes.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrds.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrod.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrss.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrur.cc")
    .file("lib/dcmtk/dcmdata/libsrc/vrscan.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcchrstr.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdict.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcistrma.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcmetinf.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcpixel.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcrlerp.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcuid.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrdt.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrof.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrst.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrus.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dccodec.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdirrec.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcistrmb.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcobject.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcpixseq.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcsequen.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrae.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrfd.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrol.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrsv.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrut.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdatset.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcelem.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcistrmf.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcostrma.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcpxitem.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcspchrs.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvras.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrfl.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrov.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrtm.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvruv.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdatutl.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcencdoc.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcistrmz.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcostrmb.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcrleccd.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcstack.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrat.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvris.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrpn.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvruc.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcwcache.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcddirif.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcerror.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcitem.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcostrmf.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcrlecce.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcswap.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvr.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrlo.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrpobw.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrui.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcxfer.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcdicdir.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcfilefo.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcjson.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcostrmz.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcrlecp.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dctag.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrcs.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrlt.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrsh.cc")
    .file("lib/dcmtk/dcmdata/libsrc/dcvrul.cc")
    .file("lib/dcmtk/dcmdata/libsrc/mkdeftag.cc")

    .file("lib/dcmtk/ofstd/libsrc/ofchrenc.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofconapp.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofconfig.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofcrc32.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofdatime.cc")
    .file("lib/dcmtk/ofstd/libsrc/offile.cc")
    .file("lib/dcmtk/ofstd/libsrc/offname.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofmath.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofsockad.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofstring.cc")
    .file("lib/dcmtk/ofstd/libsrc/oftempf.cc")
    .file("lib/dcmtk/ofstd/libsrc/oftime.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofuuid.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofcmdln.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofcond.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofconsol.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofdate.cc")
    .file("lib/dcmtk/ofstd/libsrc/oferror.cc")
    .file("lib/dcmtk/ofstd/libsrc/offilsys.cc")
    .file("lib/dcmtk/ofstd/libsrc/oflist.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofrand.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofstd.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofstrutl.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofthread.cc")
    .file("lib/dcmtk/ofstd/libsrc/oftimer.cc")
    .file("lib/dcmtk/ofstd/libsrc/ofxml.cc")

    .file("lib/dcmtk/oflog/libsrc/apndimpl.cc")
    .file("lib/dcmtk/oflog/libsrc/config.cc")
    .file("lib/dcmtk/oflog/libsrc/fileap.cc")
    .file("lib/dcmtk/oflog/libsrc/hierlock.cc")
    .file("lib/dcmtk/oflog/libsrc/logevent.cc")
    .file("lib/dcmtk/oflog/libsrc/logmacro.cc")
    .file("lib/dcmtk/oflog/libsrc/objreg.cc")
    .file("lib/dcmtk/oflog/libsrc/queue.cc")
    .file("lib/dcmtk/oflog/libsrc/socketap.cc")
    .file("lib/dcmtk/oflog/libsrc/striconv.cc")
    .file("lib/dcmtk/oflog/libsrc/tls.cc")
    .file("lib/dcmtk/oflog/libsrc/winsock.cc")

    .file("lib/dcmtk/oflog/libsrc/appender.cc")
    .file("lib/dcmtk/oflog/libsrc/consap.cc")
    .file("lib/dcmtk/oflog/libsrc/fileinfo.cc")
    .file("lib/dcmtk/oflog/libsrc/layout.cc")
    .file("lib/dcmtk/oflog/libsrc/logger.cc")
    .file("lib/dcmtk/oflog/libsrc/mdc.cc")
    .file("lib/dcmtk/oflog/libsrc/oflog.cc")
    .file("lib/dcmtk/oflog/libsrc/rootlog.cc")
    .file("lib/dcmtk/oflog/libsrc/socket.cc")
    .file("lib/dcmtk/oflog/libsrc/syncprims.cc")
    .file("lib/dcmtk/oflog/libsrc/unixsock.cc")

    .file("lib/dcmtk/oflog/libsrc/asyncap.cc")
    //.file("lib/dcmtk/oflog/libsrc/cygwin32.cc")
    .file("lib/dcmtk/oflog/libsrc/filter.cc")
    .file("lib/dcmtk/oflog/libsrc/lloguser.cc")
    .file("lib/dcmtk/oflog/libsrc/logimpl.cc")
    .file("lib/dcmtk/oflog/libsrc/ndc.cc")
    .file("lib/dcmtk/oflog/libsrc/patlay.cc")
    .file("lib/dcmtk/oflog/libsrc/sleep.cc")
    .file("lib/dcmtk/oflog/libsrc/strccloc.cc")
    .file("lib/dcmtk/oflog/libsrc/syslogap.cc")
    .file("lib/dcmtk/oflog/libsrc/version.cc")

    //.file("lib/dcmtk/oflog/libsrc/clfsap.cc")
    .file("lib/dcmtk/oflog/libsrc/env.cc")
    .file("lib/dcmtk/oflog/libsrc/globinit.cc")
    .file("lib/dcmtk/oflog/libsrc/lockfile.cc")
    .file("lib/dcmtk/oflog/libsrc/loglevel.cc")
    .file("lib/dcmtk/oflog/libsrc/ntelogap.cc")
    .file("lib/dcmtk/oflog/libsrc/pointer.cc")
    .file("lib/dcmtk/oflog/libsrc/snprintf.cc")
    .file("lib/dcmtk/oflog/libsrc/strcloc.cc")
    .file("lib/dcmtk/oflog/libsrc/threads.cc")
    .file("lib/dcmtk/oflog/libsrc/winconap.cc")

    .file("lib/dcmtk/oflog/libsrc/clogger.cc")
    .file("lib/dcmtk/oflog/libsrc/factory.cc")
    .file("lib/dcmtk/oflog/libsrc/hierarchy.cc")
    .file("lib/dcmtk/oflog/libsrc/log4judp.cc")
    .file("lib/dcmtk/oflog/libsrc/loglog.cc")
    .file("lib/dcmtk/oflog/libsrc/nullap.cc")
    .file("lib/dcmtk/oflog/libsrc/property.cc")
    .file("lib/dcmtk/oflog/libsrc/sockbuff.cc")
    .file("lib/dcmtk/oflog/libsrc/strhelp.cc")
    .file("lib/dcmtk/oflog/libsrc/timehelp.cc")
    .file("lib/dcmtk/oflog/libsrc/windebap.cc")

    .define("oflog_EXPORTS", None)

    .compile("libdcmtk_static");
}