[package]
name = "dcmtk"
version = "0.0.1"
build = "build.rs"

[dependencies]
libc = "0.2"
cpp = "0.5"

[build-dependencies]
cpp_build = "0.5"
#cc = { version = "1.0.0", features = ["parallel"] }
cc = "1.0.0"